doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: User
            Household:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Household/Entity'
                prefix: 'App\Household\Entity'
                alias: Household
            RefreshToken:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: Auth
            Todo:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Todo/Entity'
                prefix: 'App\Todo\Entity'
                alias: Todo
            Task:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Task/Entity'
                prefix: 'App\Task\Entity'
                alias: Task
            PasswordReset:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/PasswordReset/Entity'
                prefix: 'App\PasswordReset\Entity'
                alias: PasswordReset
            Push:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Push/Entity'
                prefix: 'App\Push\Entity'
                alias: Push
            Registration:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Registration/Entity'
                prefix: 'App\Registration\Entity'
                alias: Registration
            Analytics:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Analytics/Entity'
                prefix: 'App\Analytics\Entity'
                alias: Analytics
